
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD AT BUILD COMMA COMMENT CREATE DOWN EDIT END EXIT GET ID INT LEFT LP MAP MOVE MOVES NAMED OBSTABLE REMOVE REPLACE RIGHT RP RUN SET SOLUTION START SWITCH TO TRAVERSE UNDO UP\n    eval : go_up\n         | end_map\n         | run_solution\n         | set_traverse\n         | go_down\n         | exit_game\n         | go_left\n         | undo_move\n         | build_map\n         | build_solution\n         | go_right\n         | start_map\n         | switch_map\n         | set_obstacle\n         | map_assign\n         | solution_assign\n         | empty\n    \n    go_up : MOVE UP\n            | MOVE UP INT\n            | MOVE UP LP INT RP\n    \n    end_map : SET END AT INT INT\n    \n    run_solution : RUN ID\n    \n    set_traverse : SET TRAVERSE TO INT INT COMMA INT INT\n    \n    go_down : MOVE DOWN\n            | MOVE DOWN INT\n            | MOVE DOWN LP INT RP\n    \n    exit_game : EXIT\n    \n    go_left : MOVE LEFT\n            | MOVE LEFT INT\n            | MOVE LEFT LP INT RP\n    \n    undo_move : UNDO\n    \n    build_map : BUILD MAP ID\n    \n    build_solution : BUILD SOLUTION ID\n    \n    go_right : MOVE RIGHT\n            | MOVE RIGHT INT\n            | MOVE RIGHT LP INT RP\n    \n    start_map : SET START AT INT INT\n    \n    switch_map : SWITCH TO ID\n    \n    set_obstacle : ADD ID AT INT INT\n                 | ADD ID AT INT COMMA INT\n                 | ADD ID AT LP INT COMMA INT RP\n    \n    map_assign : CREATE MAP NAMED ID\n    \n    solution_assign : CREATE SOLUTION NAMED ID\n    \n    empty :\n    '
    
_lr_action_items = {'MOVE':([0,],[19,]),'SET':([0,],[20,]),'RUN':([0,],[21,]),'EXIT':([0,],[22,]),'UNDO':([0,],[23,]),'BUILD':([0,],[24,]),'SWITCH':([0,],[25,]),'ADD':([0,],[26,]),'CREATE':([0,],[27,]),'$end':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,22,23,28,29,30,31,35,42,44,46,48,53,54,55,68,69,70,71,72,73,74,76,77,81,85,86,],[-44,0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-27,-31,-18,-24,-28,-34,-22,-19,-25,-29,-35,-32,-33,-38,-42,-43,-20,-26,-30,-36,-21,-37,-39,-40,-23,-41,]),'UP':([19,],[28,]),'DOWN':([19,],[29,]),'LEFT':([19,],[30,]),'RIGHT':([19,],[31,]),'END':([20,],[32,]),'TRAVERSE':([20,],[33,]),'START':([20,],[34,]),'ID':([21,26,36,37,38,57,58,],[35,39,53,54,55,68,69,]),'MAP':([24,27,],[36,40,]),'SOLUTION':([24,27,],[37,41,]),'TO':([25,33,],[38,51,]),'INT':([28,29,30,31,43,45,47,49,50,51,52,56,63,64,65,66,67,78,80,82,83,],[42,44,46,48,59,60,61,62,63,64,65,66,74,75,76,77,79,81,83,84,85,]),'LP':([28,29,30,31,56,],[43,45,47,49,67,]),'AT':([32,34,39,],[50,52,56,]),'NAMED':([40,41,],[57,58,]),'RP':([59,60,61,62,84,],[70,71,72,73,86,]),'COMMA':([66,75,79,],[78,80,82,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'eval':([0,],[1,]),'go_up':([0,],[2,]),'end_map':([0,],[3,]),'run_solution':([0,],[4,]),'set_traverse':([0,],[5,]),'go_down':([0,],[6,]),'exit_game':([0,],[7,]),'go_left':([0,],[8,]),'undo_move':([0,],[9,]),'build_map':([0,],[10,]),'build_solution':([0,],[11,]),'go_right':([0,],[12,]),'start_map':([0,],[13,]),'switch_map':([0,],[14,]),'set_obstacle':([0,],[15,]),'map_assign':([0,],[16,]),'solution_assign':([0,],[17,]),'empty':([0,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> eval","S'",1,None,None,None),
  ('eval -> go_up','eval',1,'p_eval','PuzzolveYacc.py',16),
  ('eval -> end_map','eval',1,'p_eval','PuzzolveYacc.py',17),
  ('eval -> run_solution','eval',1,'p_eval','PuzzolveYacc.py',18),
  ('eval -> set_traverse','eval',1,'p_eval','PuzzolveYacc.py',19),
  ('eval -> go_down','eval',1,'p_eval','PuzzolveYacc.py',20),
  ('eval -> exit_game','eval',1,'p_eval','PuzzolveYacc.py',21),
  ('eval -> go_left','eval',1,'p_eval','PuzzolveYacc.py',22),
  ('eval -> undo_move','eval',1,'p_eval','PuzzolveYacc.py',23),
  ('eval -> build_map','eval',1,'p_eval','PuzzolveYacc.py',24),
  ('eval -> build_solution','eval',1,'p_eval','PuzzolveYacc.py',25),
  ('eval -> go_right','eval',1,'p_eval','PuzzolveYacc.py',26),
  ('eval -> start_map','eval',1,'p_eval','PuzzolveYacc.py',27),
  ('eval -> switch_map','eval',1,'p_eval','PuzzolveYacc.py',28),
  ('eval -> set_obstacle','eval',1,'p_eval','PuzzolveYacc.py',29),
  ('eval -> map_assign','eval',1,'p_eval','PuzzolveYacc.py',30),
  ('eval -> solution_assign','eval',1,'p_eval','PuzzolveYacc.py',31),
  ('eval -> empty','eval',1,'p_eval','PuzzolveYacc.py',32),
  ('go_up -> MOVE UP','go_up',2,'p_go_up','PuzzolveYacc.py',38),
  ('go_up -> MOVE UP INT','go_up',3,'p_go_up','PuzzolveYacc.py',39),
  ('go_up -> MOVE UP LP INT RP','go_up',5,'p_go_up','PuzzolveYacc.py',40),
  ('end_map -> SET END AT INT INT','end_map',5,'p_end_map','PuzzolveYacc.py',55),
  ('run_solution -> RUN ID','run_solution',2,'p_run_solution','PuzzolveYacc.py',64),
  ('set_traverse -> SET TRAVERSE TO INT INT COMMA INT INT','set_traverse',8,'p_set_traverse','PuzzolveYacc.py',70),
  ('go_down -> MOVE DOWN','go_down',2,'p_go_down','PuzzolveYacc.py',80),
  ('go_down -> MOVE DOWN INT','go_down',3,'p_go_down','PuzzolveYacc.py',81),
  ('go_down -> MOVE DOWN LP INT RP','go_down',5,'p_go_down','PuzzolveYacc.py',82),
  ('exit_game -> EXIT','exit_game',1,'p_exit_game','PuzzolveYacc.py',102),
  ('go_left -> MOVE LEFT','go_left',2,'p_go_left','PuzzolveYacc.py',115),
  ('go_left -> MOVE LEFT INT','go_left',3,'p_go_left','PuzzolveYacc.py',116),
  ('go_left -> MOVE LEFT LP INT RP','go_left',5,'p_go_left','PuzzolveYacc.py',117),
  ('undo_move -> UNDO','undo_move',1,'p_undo_move','PuzzolveYacc.py',132),
  ('build_map -> BUILD MAP ID','build_map',3,'p_build_map','PuzzolveYacc.py',141),
  ('build_solution -> BUILD SOLUTION ID','build_solution',3,'p_build_solution','PuzzolveYacc.py',153),
  ('go_right -> MOVE RIGHT','go_right',2,'p_go_right','PuzzolveYacc.py',165),
  ('go_right -> MOVE RIGHT INT','go_right',3,'p_go_right','PuzzolveYacc.py',166),
  ('go_right -> MOVE RIGHT LP INT RP','go_right',5,'p_go_right','PuzzolveYacc.py',167),
  ('start_map -> SET START AT INT INT','start_map',5,'p_start_map','PuzzolveYacc.py',188),
  ('switch_map -> SWITCH TO ID','switch_map',3,'p_switch_map','PuzzolveYacc.py',198),
  ('set_obstacle -> ADD ID AT INT INT','set_obstacle',5,'p_set_obstacle','PuzzolveYacc.py',211),
  ('set_obstacle -> ADD ID AT INT COMMA INT','set_obstacle',6,'p_set_obstacle','PuzzolveYacc.py',212),
  ('set_obstacle -> ADD ID AT LP INT COMMA INT RP','set_obstacle',8,'p_set_obstacle','PuzzolveYacc.py',213),
  ('map_assign -> CREATE MAP NAMED ID','map_assign',4,'p_map_assign','PuzzolveYacc.py',229),
  ('solution_assign -> CREATE SOLUTION NAMED ID','solution_assign',4,'p_solution_assign','PuzzolveYacc.py',240),
  ('empty -> <empty>','empty',0,'p_empty','PuzzolveYacc.py',252),
]
